---
version: '3.7'

services:

  rabbitmq-01:
    image: rabbitmq:3.7.18-management
    hostname: rabbitmq-01
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=Passw0rd
      - RABBITMQ_ERLANG_COOKIE="MY-SECRET-KEY-123"
    labels:
      SERVICE_NAME: rabbitmq
      SERVICE_TAGS: mq
    ports:
      - target: 15672
        published: 15672
        protocol: tcp
        mode: host
    networks:
      - internal_overlay
    volumes:
      - rabbitmq-01-data:/var/lib/rabbitmq
    deploy:
      labels:
        # traefik v2 configs
        traefik.http.routers.rabbitmq.rule: Host(`rabbitmq.docker.devlocal`)
        traefik.http.services.rabbitmq-service.loadbalancer.server.port: 15672

  rabbitmq-02:
    image: rabbitmq:3.7.18-management
    hostname: rabbitmq-02
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=Passw0rd
      - RABBITMQ_ERLANG_COOKIE="MY-SECRET-KEY-123"
    labels:
      SERVICE_NAME: rabbitmq
      SERVICE_TAGS: mq
    networks:
      - internal_overlay
    volumes:
      - rabbitmq-02-data:/var/lib/rabbitmq

  rabbitmq-03:
    image: rabbitmq:3.7.18-management
    hostname: rabbitmq-03
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=Passw0rd
      - RABBITMQ_ERLANG_COOKIE="MY-SECRET-KEY-123"
    labels:
      SERVICE_NAME: rabbitmq
      SERVICE_TAGS: mq
    networks:
      - internal_overlay
    volumes:
      - rabbitmq-03-data:/var/lib/rabbitmq

networks:
  internal_overlay:
    external: true

volumes:
  rabbitmq-01-data:
  rabbitmq-02-data:
  rabbitmq-03-data:
